import jsPDF from 'jspdf';
import { AnomalyEvent } from '../types/dashboard';

export const useReportExport = () => {
    const generateReport = (anomaly: AnomalyEvent, resolved: boolean = false) => {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // --- Header ---
        doc.setFillColor(15, 23, 42); // Slate 900
        doc.rect(0, 0, pageWidth, 40, 'F');

        doc.setTextColor(34, 197, 94); // Green 500
        doc.setFontSize(22);
        doc.setFont('courier', 'bold');
        doc.text("ASTRAGUARD MISSION REPORT", 20, 20);

        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184); // Slate 400
        doc.text(`DATE: ${new Date().toISOString()}`, 20, 30);
        doc.text("CLASSIFICATION: TOP SECRET // EYES ONLY", pageWidth - 20, 30, { align: 'right' });

        // --- Incident Details ---
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.text("INCIDENT SUMMARY", 20, 60);

        doc.setDrawColor(0, 0, 0);
        doc.line(20, 62, pageWidth - 20, 62);

        doc.setFont('courier', 'normal');
        doc.setFontSize(12);

        let y = 80;
        const lineHeight = 10;

        doc.text(`ANOMALY ID:   ${anomaly.id}`, 20, y); y += lineHeight;
        doc.text(`SEVERITY:     ${anomaly.severity.toUpperCase()}`, 20, y); y += lineHeight;
        doc.text(`SATELLITE:    ${anomaly.satellite}`, 20, y); y += lineHeight;
        doc.text(`DETECTED AT:  ${anomaly.timestamp}`, 20, y); y += lineHeight;
        doc.text(`METRIC:       ${anomaly.metric}`, 20, y); y += lineHeight;
        doc.text(`VALUE:        ${anomaly.value}`, 20, y); y += lineHeight;
        doc.text(`STATUS:       ${resolved ? 'RESOLVED' : 'ACTIVE'}`, 20, y); y += lineHeight * 2;

        // --- Simulated Analysis ---
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.text("SYSTEM ANALYSIS", 20, y);
        y += 2;
        doc.line(20, y, pageWidth - 20, y);
        y += 15;

        doc.setFont('courier', 'normal');
        doc.setFontSize(11);
        const analysisText =
            `Automated diagnostic scan completed. The anomaly detected in ${anomaly.satellite} indicates a deviation ` +
            `in ${anomaly.metric} operating parameters. ${resolved ? 'Operator intervention has successfully normalized the system.' : 'Immediate attention required.'} ` +
            `Telemetry suggests potential interference or component degradation. Continue monitoring thermal sub-systems.`;

        const splitText = doc.splitTextToSize(analysisText, pageWidth - 40);
        doc.text(splitText, 20, y);

        // --- Footer ---
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFillColor(15, 23, 42);
        doc.rect(0, pageHeight - 20, pageWidth, 20, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.text("GENERATED BY ASTRAGUARD AI CORE v4.2.0", pageWidth / 2, pageHeight - 8, { align: 'center' });

        doc.save(`AstraGuard_Report_${anomaly.id}.pdf`);
    };

    return { generateReport };
};
